# Use an existing docker image as a base
From alpine

# Download and install a dependancy
Run apk add --update redis

Run apk add --update gcc

# Tell the image what to do when it starts as a container
CMD ["redis-server"]